apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.26.0
        command: ["/cloud_sql_proxy",
                  "-instances=canvas-chariot-428823-b8:asia-northeast3:dump=tcp:3306",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
        - name: cloudsql-instance-credentials
          mountPath: /secrets/cloudsql
          readOnly: true
      - name: php-app
        image: gcr.io/canvas-chariot-428823-b8/php-app:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 20m
          limits:
            cpu: 50m
        env:
        - name: DB_HOST
          value: "127.0.0.1"  # Cloud SQL 프록시가 로컬 호스트를 사용하므로
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db-user
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db-password
        - name: DB_NAME
          value: "exam_db"
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
